
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Marco Antonio
 */
public class SetMapa extends javax.swing.JDialog {
    int maxx = 0, maxy = 0;
    /**
     * Creates new form SetMapa
     */
    public SetMapa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public int getMaxx() {
        return maxx;
    }

    public int getMaxy() {
        return maxy;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMapa = new javax.swing.JPanel();
        jLColunas = new javax.swing.JLabel();
        jLLinhas = new javax.swing.JLabel();
        jTFLinhas = new javax.swing.JTextField();
        jTFColunas = new javax.swing.JTextField();
        jBExit = new javax.swing.JButton();
        jBSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SetMapa");

        jPMapa.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurando:"));

        jLColunas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLColunas.setText("Quantidade de Colunas:");

        jLLinhas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLLinhas.setText("Quantidade de Linhas:");

        jTFLinhas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focado(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                desfocado(evt);
            }
        });
        jTFLinhas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFLinhasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaLinhas(evt);
            }
        });

        jTFColunas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focado(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                desfocado(evt);
            }
        });
        jTFColunas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFColunasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaColunas(evt);
            }
        });

        javax.swing.GroupLayout jPMapaLayout = new javax.swing.GroupLayout(jPMapa);
        jPMapa.setLayout(jPMapaLayout);
        jPMapaLayout.setHorizontalGroup(
            jPMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMapaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPMapaLayout.createSequentialGroup()
                        .addComponent(jLLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPMapaLayout.createSequentialGroup()
                        .addComponent(jLColunas)
                        .addGap(18, 22, Short.MAX_VALUE)
                        .addComponent(jTFColunas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPMapaLayout.setVerticalGroup(
            jPMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMapaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLLinhas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLColunas)
                    .addComponent(jTFColunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jBExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBExit.setText("Sair sem salvar");
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        jBSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBSave.setText("Salvar");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSave)
                    .addComponent(jBExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void focado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focado
        if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            campo.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_focado

    private void desfocado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_desfocado
        if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            campo.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_desfocado

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBExitActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        if (jTFLinhas.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe quantidade de linhas", "Warning", 0);
            jTFLinhas.requestFocusInWindow();
            return;
        }
        
        if (jTFColunas.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe quantidade de colunas", "Warning", 0);
            jTFColunas.requestFocusInWindow();
            return;
        }
        
        int opc = JOptionPane.showConfirmDialog(this, "Dados preenchidos. Validar?", "SetMapa", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null);
        if(opc == 0)
        {
            //Criação do Mapa
            maxx = Integer.parseInt(jTFLinhas.getText());
            maxy = Integer.parseInt(jTFColunas.getText());
            jTFLinhas.setText(null);
            jTFColunas.setText(null);
            setVisible(false);
        }
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jTFLinhasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFLinhasKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jTFColunas.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTFLinhasKeyPressed

    private void jTFColunasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFColunasKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jTFLinhas.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTFColunasKeyPressed

    private void validaLinhas(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaLinhas
        char campo = evt.getKeyChar();
        if(!Character.isDigit(campo)&&(campo != KeyEvent.VK_BACK_SPACE)&&(campo != KeyEvent.VK_DELETE)&&(campo != KeyEvent.VK_ENTER))
        {
            JOptionPane.showMessageDialog(this, "Não inserir caracteres", "Warning", 0);
            evt.consume();
        }
    }//GEN-LAST:event_validaLinhas

    private void validaColunas(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaColunas
        char campo = evt.getKeyChar();
        if(!Character.isDigit(campo)&&(campo != KeyEvent.VK_BACK_SPACE)&&(campo != KeyEvent.VK_DELETE)&&(campo != KeyEvent.VK_ENTER))
        {
            JOptionPane.showMessageDialog(this, "Não inserir caracteres", "Warning", 0);
            evt.consume();
        }
    }//GEN-LAST:event_validaColunas

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBSave;
    private javax.swing.JLabel jLColunas;
    private javax.swing.JLabel jLLinhas;
    private javax.swing.JPanel jPMapa;
    private javax.swing.JTextField jTFColunas;
    private javax.swing.JTextField jTFLinhas;
    // End of variables declaration//GEN-END:variables
}
