
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Marco Antonio
 */
public class SetOrigem extends javax.swing.JDialog {

    Random r = new Random();
    Node origem = null;
    int[][] matrizAux;
    
    public SetOrigem(java.awt.Frame parent, boolean modal, int[][] matriz) {
        super(parent, modal);
        initComponents();
        jTFLinha.setBackground(Color.DARK_GRAY);
        jTFColuna.setBackground(Color.DARK_GRAY);
        matrizAux = matriz;
    }

    public Node getOrigem() {
        return origem;
    }

    public int[][] getMatrizAux() {
        return matrizAux;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGRandom = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRBS = new javax.swing.JRadioButton();
        jRBN = new javax.swing.JRadioButton();
        jLRandom = new javax.swing.JLabel();
        jLLinha = new javax.swing.JLabel();
        jLColuna = new javax.swing.JLabel();
        jTFLinha = new javax.swing.JTextField();
        jTFColuna = new javax.swing.JTextField();
        jBExit = new javax.swing.JButton();
        jBSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SetOrigem");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurando:"));

        bGRandom.add(jRBS);
        jRBS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRBS.setText("Sim");
        jRBS.setActionCommand("S");
        jRBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSActionPerformed(evt);
            }
        });

        bGRandom.add(jRBN);
        jRBN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRBN.setText("Não");
        jRBN.setActionCommand("N");
        jRBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNActionPerformed(evt);
            }
        });

        jLRandom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLRandom.setText("Gerar Randomicamente?");

        jLLinha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLLinha.setText("Quantidade de Linhas:");

        jLColuna.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLColuna.setText("Quantidade de Colunas:");

        jTFLinha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFLinhafocado(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFLinhadesfocado(evt);
            }
        });
        jTFLinha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFLinhaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFLinhavalidaLinhas(evt);
            }
        });

        jTFColuna.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFColunafocado(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFColunadesfocado(evt);
            }
        });
        jTFColuna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFColunaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFColunavalidaColunas(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLColuna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBN)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFColuna, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBS)
                    .addComponent(jRBN)
                    .addComponent(jLRandom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLColuna)
                    .addComponent(jTFLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLinha)
                    .addComponent(jTFColuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBExit.setText("Sair sem salvar");
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        jBSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBSave.setText("Salvar");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBExit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSave)
                    .addComponent(jBExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBExitActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        if(bGRandom.getSelection()!=null){
            int x, y;
            if(bGRandom.getSelection().getActionCommand().charAt(0)=='N'){
                if (jTFLinha.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Informe em que linha a origem está", "Warning", 0);
                    jTFLinha.requestFocusInWindow();
                    return;
                }

                if (jTFColuna.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Informe em que coluna a origem está", "Warning", 0);
                    jTFColuna.requestFocusInWindow();
                    return;
                }
                
                x = Integer.parseInt(jTFLinha.getText());
                y = Integer.parseInt(jTFColuna.getText());
                
                if(x >=matrizAux.length){
                    JOptionPane.showMessageDialog(this, "Linha extrapola o limite estipulado", "Warning", 0);
                    jTFLinha.requestFocusInWindow();
                    return;
                }
                
                if(y >=matrizAux[0].length){
                    JOptionPane.showMessageDialog(this, "Coluna extrapola o limite estipulado", "Warning", 0);
                    jTFLinha.requestFocusInWindow();
                    return;
                }
                
            }else{
                x = r.nextInt(matrizAux.length);
                y = r.nextInt(matrizAux[0].length);
            }
            int opc = JOptionPane.showConfirmDialog(this, "Dados preenchidos. Validar?", "SetOrigem", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null);
            if(opc == 0) {
                //Criação do No
                origem = new Node(x, y,0);
                matrizAux[x][y]=3;
                jTFLinha.setText(null);
                jTFColuna.setText(null);
                setVisible(false);
            }
        }else JOptionPane.showMessageDialog(this, "Seleção não realizada", "Warning", 0);
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jTFLinhafocado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFLinhafocado
        if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            if(campo.getBackground()==Color.DARK_GRAY) return;
            campo.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_jTFLinhafocado

    private void jTFLinhadesfocado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFLinhadesfocado
        if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            if(campo.getBackground()==Color.DARK_GRAY)  return;
            campo.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jTFLinhadesfocado

    private void jTFLinhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFLinhaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jTFColuna.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTFLinhaKeyPressed

    private void jTFLinhavalidaLinhas(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFLinhavalidaLinhas
        if(evt.getSource() instanceof javax.swing.JTextField objeto){
            if(objeto.getBackground()==Color.DARK_GRAY) evt.consume();
            else{
                char campo = evt.getKeyChar();
                if(!Character.isDigit(campo)&&(campo != KeyEvent.VK_BACK_SPACE)&&(campo != KeyEvent.VK_DELETE)&&(campo != KeyEvent.VK_ENTER))
                {
                    JOptionPane.showMessageDialog(this, "Não inserir caracteres", "Warning", 0);
                    evt.consume();
                }
            }
        }
    }//GEN-LAST:event_jTFLinhavalidaLinhas

    private void jTFColunafocado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFColunafocado
        if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            if(campo.getBackground()==Color.DARK_GRAY)  return;
            campo.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_jTFColunafocado

    private void jTFColunadesfocado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFColunadesfocado
        if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            if(campo.getBackground()==Color.DARK_GRAY)  return;
            campo.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jTFColunadesfocado

    private void jTFColunaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFColunaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jTFLinha.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTFColunaKeyPressed

    private void jTFColunavalidaColunas(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFColunavalidaColunas
        if(evt.getSource() instanceof javax.swing.JTextField objeto){
            if(objeto.getBackground()==Color.DARK_GRAY) evt.consume();
            else{
                char campo = evt.getKeyChar();
                if(!Character.isDigit(campo)&&(campo != KeyEvent.VK_BACK_SPACE)&&(campo != KeyEvent.VK_DELETE)&&(campo != KeyEvent.VK_ENTER))
                {
                    JOptionPane.showMessageDialog(this, "Não inserir caracteres", "Warning", 0);
                    evt.consume();
                }
            }
        }
    }//GEN-LAST:event_jTFColunavalidaColunas

    private void jRBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSActionPerformed
        jTFColuna.setBackground(Color.DARK_GRAY);
        jTFLinha.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jRBSActionPerformed

    private void jRBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNActionPerformed
        jTFColuna.setBackground(Color.WHITE);
        jTFLinha.setBackground(Color.WHITE);
    }//GEN-LAST:event_jRBNActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGRandom;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBSave;
    private javax.swing.JLabel jLColuna;
    private javax.swing.JLabel jLLinha;
    private javax.swing.JLabel jLRandom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBN;
    private javax.swing.JRadioButton jRBS;
    private javax.swing.JTextField jTFColuna;
    private javax.swing.JTextField jTFLinha;
    // End of variables declaration//GEN-END:variables
}
