
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Marco Antonio
 */
public class SetQTDDestino extends javax.swing.JDialog {

    Random r = new Random();
    ListaInput input = new ListaInput();
    ListaPInput inputP = new ListaPInput();
    int[][] matrizAux;
    boolean ponderadoAux;
    
    public SetQTDDestino(java.awt.Frame parent, boolean modal, int[][]matriz, boolean ponderado) {
        super(parent, modal);
        initComponents();
        matrizAux = matriz;
        ponderadoAux = ponderado;
    }

    public ListaInput getInput() {
        return input;
    }

    public ListaPInput getInputP() {
        return inputP;
    }
    
    public int[][] getMatrizAux() {
        return matrizAux;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMapa = new javax.swing.JPanel();
        jLDestinos = new javax.swing.JLabel();
        jTFDestinos = new javax.swing.JTextField();
        jBSave = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SetDestino");

        jPMapa.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurando:"));

        jLDestinos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLDestinos.setText("Quantidade de Destinos:");

        jTFDestinos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDestinosfocado(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFDestinosdesfocado(evt);
            }
        });
        jTFDestinos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFValidaDestinos(evt);
            }
        });

        javax.swing.GroupLayout jPMapaLayout = new javax.swing.GroupLayout(jPMapa);
        jPMapa.setLayout(jPMapaLayout);
        jPMapaLayout.setHorizontalGroup(
            jPMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMapaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLDestinos)
                .addGap(18, 18, 18)
                .addComponent(jTFDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPMapaLayout.setVerticalGroup(
            jPMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMapaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDestinos)
                    .addComponent(jTFDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBSave.setText("Salvar");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jBExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBExit.setText("Sair sem salvar");
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBExit))
                    .addComponent(jPMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSave)
                    .addComponent(jBExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDestinosfocado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDestinosfocado
        if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            campo.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_jTFDestinosfocado

    private void jTFDestinosdesfocado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDestinosdesfocado
        if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            campo.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jTFDestinosdesfocado

    private void jTFValidaDestinos(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFValidaDestinos
        char campo = evt.getKeyChar();
        if(!Character.isDigit(campo)&&(campo != KeyEvent.VK_BACK_SPACE)&&(campo != KeyEvent.VK_DELETE)&&(campo != KeyEvent.VK_ENTER))
        {
            JOptionPane.showMessageDialog(this, "Não inserir caracteres", "Warning", 0);
            evt.consume();
        }else if(campo == KeyEvent.VK_0){
            JOptionPane.showMessageDialog(this, "Não inserir valores nulos", "Warning", 0);
            evt.consume();
        }
    }//GEN-LAST:event_jTFValidaDestinos

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        int limite;
        if (jTFDestinos.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe quantidade de destinos", "Warning", 0);
            jTFDestinos.requestFocusInWindow();
            return;
        }else{
            limite = Integer.parseInt(jTFDestinos.getText());
        }
        
        if(limite>(matrizAux[0].length*matrizAux.length-1)){
            JOptionPane.showMessageDialog(this, "Quantidade de Destinos extrapola a quantidade de espaços vazios da matriz", "Warning", 0);
            jTFDestinos.requestFocusInWindow();
            return;
        }

        int opc = JOptionPane.showConfirmDialog(this, "Dados preenchidos. Validar?", "SetMapa", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null);
        if(opc == 0)
        {
            int count=0,x , y;
            
            Node aux; NodeP auxP;
            
            while(count < limite){
                x = r.nextInt(matrizAux.length);
                y = r.nextInt(matrizAux[0].length);
                
                if(matrizAux[x][y]==0){
                    if(!ponderadoAux){
                        aux = new Node(x,y);
                        input.add(aux);
                    }else{
                        auxP = new NodeP(x, y);
                        inputP.add(auxP);
                    }
                    matrizAux[x][y]=4;
                    count++;
                }
            }
            jTFDestinos.setText(null);
            setVisible(false);
        }
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBExitActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBSave;
    private javax.swing.JLabel jLDestinos;
    private javax.swing.JPanel jPMapa;
    private javax.swing.JTextField jTFDestinos;
    // End of variables declaration//GEN-END:variables
}
