package GUI;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import sistemabancario.ContaCorrente;
import sistemabancario.ContaEspecial;
import sistemabancario.Pessoa;

public class SistemaBancarioGUI extends javax.swing.JFrame {

    public SistemaBancarioGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private ContaCorrente conta;
    private Pessoa ps;
    boolean aberto = false;
    boolean spc;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDados = new javax.swing.JPanel();
        jLNConta = new javax.swing.JLabel();
        jLNTitular = new javax.swing.JLabel();
        jLSNTitular = new javax.swing.JLabel();
        jLTConta = new javax.swing.JLabel();
        jRBSimples = new javax.swing.JRadioButton();
        jRBEspecial = new javax.swing.JRadioButton();
        jTFNConta = new javax.swing.JTextField();
        jTFNTitular = new javax.swing.JTextField();
        jTFSNTitular = new javax.swing.JTextField();
        jPOp = new javax.swing.JPanel();
        jBDepositar = new javax.swing.JButton();
        jBSacar = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBAbrir = new javax.swing.JButton();
        jPInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados:"));

        jLNConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLNConta.setText("Número da Conta:");

        jLNTitular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLNTitular.setText("Nome do Titular:");

        jLSNTitular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLSNTitular.setText("Sobrenome do titular:");

        jLTConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLTConta.setText("Tipo de Conta:");

        jRBSimples.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRBSimples.setText("Simples");
        jRBSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSimplesActionPerformed(evt);
            }
        });

        jRBEspecial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRBEspecial.setText("Especial");
        jRBEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEspecialActionPerformed(evt);
            }
        });

        jTFNConta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Focado(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Desfocado(evt);
            }
        });
        jTFNConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNContaKeyPressed(evt);
            }
        });

        jTFNTitular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Focado(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Desfocado(evt);
            }
        });
        jTFNTitular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNTitularKeyPressed(evt);
            }
        });

        jTFSNTitular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Focado(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Desfocado(evt);
            }
        });
        jTFSNTitular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFSNTitularKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPDadosLayout = new javax.swing.GroupLayout(jPDados);
        jPDados.setLayout(jPDadosLayout);
        jPDadosLayout.setHorizontalGroup(
            jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLSNTitular, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jLNTitular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLNConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPDadosLayout.createSequentialGroup()
                        .addComponent(jRBSimples)
                        .addGap(18, 18, 18)
                        .addComponent(jRBEspecial))
                    .addComponent(jTFNConta)
                    .addComponent(jTFNTitular)
                    .addComponent(jTFSNTitular))
                .addGap(16, 16, 16))
        );
        jPDadosLayout.setVerticalGroup(
            jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNConta)
                    .addComponent(jTFNConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNTitular)
                    .addComponent(jTFNTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSNTitular)
                    .addComponent(jTFSNTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTConta)
                    .addComponent(jRBSimples)
                    .addComponent(jRBEspecial))
                .addGap(40, 40, 40))
        );

        jPOp.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações:"));

        jBDepositar.setText("Depositar");
        jBDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDepositarActionPerformed(evt);
            }
        });

        jBSacar.setText("Sacar");
        jBSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSacarActionPerformed(evt);
            }
        });

        jBLimpar.setText("Limpar Campos");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBAbrir.setText("Abertura de Conta");
        jBAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOpLayout = new javax.swing.GroupLayout(jPOp);
        jPOp.setLayout(jPOpLayout);
        jPOpLayout.setHorizontalGroup(
            jPOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBDepositar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPOpLayout.setVerticalGroup(
            jPOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jBAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações:"));

        jTAInfo.setColumns(20);
        jTAInfo.setRows(5);
        jScrollPane1.setViewportView(jTAInfo);

        javax.swing.GroupLayout jPInfoLayout = new javax.swing.GroupLayout(jPInfo);
        jPInfo.setLayout(jPInfoLayout);
        jPInfoLayout.setHorizontalGroup(
            jPInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPInfoLayout.setVerticalGroup(
            jPInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNContaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNContaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jTFNTitular.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTFNContaKeyPressed

    private void jTFNTitularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNTitularKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jTFSNTitular.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTFNTitularKeyPressed

    private void jTFSNTitularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSNTitularKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jTFNConta.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTFSNTitularKeyPressed

    private void Focado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Focado
        if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            campo.setBackground(new Color(184, 207, 229));
        }
    }//GEN-LAST:event_Focado

    private void Desfocado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Desfocado
         if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            campo.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_Desfocado

    private void jRBSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSimplesActionPerformed
        jRBEspecial.setSelected(false);
        spc = false;
    }//GEN-LAST:event_jRBSimplesActionPerformed

    private void jRBEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEspecialActionPerformed
        jRBSimples.setSelected(false);
        spc = true;
    }//GEN-LAST:event_jRBEspecialActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        jTFNTitular.setText(null);
        jTFSNTitular.setText(null);
        jTFNConta.setText(null);
        jRBEspecial.setSelected(false);
        jRBSimples.setSelected(false);
        jTAInfo.setText(null);
        jTFNTitular.requestFocusInWindow();
        aberto = false;
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jBDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDepositarActionPerformed
        if(aberto)
        {
            conta.deposito(100.0);
            jTAInfo.setText(conta.toString());
        }
    }//GEN-LAST:event_jBDepositarActionPerformed

    private void jBSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSacarActionPerformed
        if(aberto)
        {
            if(conta.saque(100.0))
            {
                jTAInfo.setText(conta.toString());
            }
        }
        
    }//GEN-LAST:event_jBSacarActionPerformed

    private void jBAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbrirActionPerformed
        if(!aberto)
        {
          if(jTFNConta.getText().trim().isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "NÚMERO não inserido", "Warning", 0);
            jTFNConta.setText(null);  //reseta o espaço
            jTFNConta.requestFocusInWindow(); //O cursor vai pro text form do nome
            return;
        }
        else if(jTFNTitular.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "NOME não inserido", "Warning", 0);
            jTFNTitular.setText(null);  //reseta o espaço
            jTFNTitular.requestFocusInWindow();
            return;
        }
        else if(jTFSNTitular.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "SOBRENOME não inserido", "Warning", 0);
            jTFNTitular.setText(null);
            jTFSNTitular.requestFocusInWindow();
            return;
        }
        else if(jTFSNTitular.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "SOBRENOME não inserido", "Warning", 0);
            jTFSNTitular.setText(null);
            jTFSNTitular.requestFocusInWindow();
            return;
        }
        else if(!jRBSimples.isEnabled()&&!jRBEspecial.isEnabled())
        {
            JOptionPane.showMessageDialog(this, "ESCOLHA não inserida", "Warning", 0);
            jRBSimples.requestFocusInWindow();
            jRBEspecial.requestFocusInWindow();
            return;
        }
        
        ps = new Pessoa(jTFNTitular.getText().trim(),jTFSNTitular.getText().trim());
        if(!spc)
        {
            conta = new ContaCorrente(jTFNConta.getText().trim(), ps);
        }
        else
        {
            conta = new ContaEspecial(jTFNConta.getText().trim(), ps);
        }
        
        jTAInfo.setText(conta.toString());
        aberto = true;  
        }
    }//GEN-LAST:event_jBAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaBancarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaBancarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaBancarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaBancarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaBancarioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAbrir;
    private javax.swing.JButton jBDepositar;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBSacar;
    private javax.swing.JLabel jLNConta;
    private javax.swing.JLabel jLNTitular;
    private javax.swing.JLabel jLSNTitular;
    private javax.swing.JLabel jLTConta;
    private javax.swing.JPanel jPDados;
    private javax.swing.JPanel jPInfo;
    private javax.swing.JPanel jPOp;
    private javax.swing.JRadioButton jRBEspecial;
    private javax.swing.JRadioButton jRBSimples;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAInfo;
    private javax.swing.JTextField jTFNConta;
    private javax.swing.JTextField jTFNTitular;
    private javax.swing.JTextField jTFSNTitular;
    // End of variables declaration//GEN-END:variables
}
