/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import code.Colecao;
import code.OperacoesComConjunto;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco Antonio
 */
public class OperaConjuntosGUI extends javax.swing.JFrame {

    private Colecao c1;
    private Colecao c2;
    private OperacoesComConjunto opc = new OperacoesComConjunto();
    
    public OperaConjuntosGUI() {
        initComponents();
        setLocationRelativeTo(null);
        jBDiferenca.setEnabled(false);
        jBInterseccao.setEnabled(false);
        jBUniao.setEnabled(false);
        jBLimpa.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPValor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFC1 = new javax.swing.JTextField();
        jTFC2 = new javax.swing.JTextField();
        jPConjuntos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAConjuntos = new javax.swing.JTextArea();
        jPOperacoes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAOperacoes = new javax.swing.JTextArea();
        jBLimpa = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jBUniao = new javax.swing.JButton();
        jBInterseccao = new javax.swing.JButton();
        jBDiferenca = new javax.swing.JButton();
        jBInstancia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPValor.setBorder(javax.swing.BorderFactory.createTitledBorder("Insere valores/tamanho do conjunto:"));

        jLabel1.setText("Conjunto 1:");

        jLabel2.setText("Conjunto 2:");

        jTFC1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Focado(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Desfocado(evt);
            }
        });
        jTFC1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFC1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validar(evt);
            }
        });

        jTFC2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Focado(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Desfocado(evt);
            }
        });
        jTFC2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFC2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validar(evt);
            }
        });

        javax.swing.GroupLayout jPValorLayout = new javax.swing.GroupLayout(jPValor);
        jPValor.setLayout(jPValorLayout);
        jPValorLayout.setHorizontalGroup(
            jPValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPValorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFC1)
                    .addComponent(jTFC2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPValorLayout.setVerticalGroup(
            jPValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPValorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPConjuntos.setBorder(javax.swing.BorderFactory.createTitledBorder("Conjuntos:"));

        jTAConjuntos.setColumns(20);
        jTAConjuntos.setRows(5);
        jScrollPane1.setViewportView(jTAConjuntos);

        javax.swing.GroupLayout jPConjuntosLayout = new javax.swing.GroupLayout(jPConjuntos);
        jPConjuntos.setLayout(jPConjuntosLayout);
        jPConjuntosLayout.setHorizontalGroup(
            jPConjuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConjuntosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPConjuntosLayout.setVerticalGroup(
            jPConjuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações:"));

        jTAOperacoes.setColumns(20);
        jTAOperacoes.setRows(5);
        jScrollPane2.setViewportView(jTAOperacoes);

        javax.swing.GroupLayout jPOperacoesLayout = new javax.swing.GroupLayout(jPOperacoes);
        jPOperacoes.setLayout(jPOperacoesLayout);
        jPOperacoesLayout.setHorizontalGroup(
            jPOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPOperacoesLayout.setVerticalGroup(
            jPOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperacoesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        jBLimpa.setText("Limpar");
        jBLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpaActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jBUniao.setText("Realizar União");
        jBUniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUniaoActionPerformed(evt);
            }
        });

        jBInterseccao.setText("Realizar Intersecção");
        jBInterseccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInterseccaoActionPerformed(evt);
            }
        });

        jBDiferenca.setText("Realizar Diferença");
        jBDiferenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDiferencaActionPerformed(evt);
            }
        });

        jBInstancia.setText("Define cojuntos");
        jBInstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInstanciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPConjuntos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBLimpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBInstancia, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jBSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBUniao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBInterseccao, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(jBDiferenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBUniao, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(jBInstancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBInterseccao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBDiferenca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPConjuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInstanciaActionPerformed
        
        if (jTFC1.getText().isEmpty()&&jTFC2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tamanho das coleções não especificado\nInsira o tamanho de ambos para prosseguir", "WARNING", 0);
            jTFC1.requestFocusInWindow();
            return;
        }
        else if(jTFC1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Tamanho da coleção 1 não especificado\nInsira o tamanho de ambos para prosseguir", "WARNING", 0);
            jTFC1.requestFocusInWindow();
            return;
        }
        else if(jTFC2.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Tamanho da coleção 2 não especificado\nInsira o tamanho de ambos para prosseguir", "WARNING", 0);
            jTFC2.requestFocusInWindow();
            return;
        }
        else{
            c1 = new Colecao(Integer.parseInt(jTFC1.getText()));
            c2 = new Colecao(Integer.parseInt(jTFC2.getText()));
                
            JOptionPane.showMessageDialog(this, "Tamanhos definidos \nUtilize os campos para realizar operações de União, Intersecção e Diferença", "ADVICE", 1);
            StringBuilder builder = new StringBuilder();
            c1.preenche();
            c2.preenche();
            builder.append(c1.dados()).append("\n").append(c2.dados());
            jTAConjuntos.setText(builder.toString());
            jBInstancia.setEnabled(false);
            jBDiferenca.setEnabled(true);
            jBInterseccao.setEnabled(true);
            jBUniao.setEnabled(true);
            jBLimpa.setEnabled(true);
            jTFC1.setText(null);
            jTFC2.setText(null);
        }
    }//GEN-LAST:event_jBInstanciaActionPerformed

    private void jTFC1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFC1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jTFC2.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTFC1KeyPressed

    private void jTFC2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFC2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jTFC1.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTFC2KeyPressed

    private void Focado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Focado
        if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            campo.setBackground(new Color(184, 207, 229));
        }
    }//GEN-LAST:event_Focado

    private void Desfocado(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Desfocado
        if(evt.getSource() instanceof javax.swing.JTextField campo)
        {
            campo.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_Desfocado

    private void jBLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpaActionPerformed
        c1.limpa();
        c2.limpa();  
        jTAConjuntos.setText(null);
        jTAOperacoes.setText(null);
        jBInstancia.setEnabled(true);
        jBDiferenca.setEnabled(false);
        jBInterseccao.setEnabled(false);
        jBUniao.setEnabled(false);
        jBLimpa.setEnabled(false);
    }//GEN-LAST:event_jBLimpaActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBUniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUniaoActionPerformed
        jTAOperacoes.setText("União:\n"+opc.uniao(c1, c2).dados());
    }//GEN-LAST:event_jBUniaoActionPerformed

    private void jBInterseccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInterseccaoActionPerformed
        jTAOperacoes.setText("Intersecção:\n"+opc.interseccao(c1, c2).dados());     
    }//GEN-LAST:event_jBInterseccaoActionPerformed

    private void jBDiferencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDiferencaActionPerformed
        jTAOperacoes.setText("Diferença:\n"+opc.diferenca(c1, c2).dados());
    }//GEN-LAST:event_jBDiferencaActionPerformed

    private void validar(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validar
        char campo = evt.getKeyChar();
        if(!Character.isDigit(campo)&&(campo != KeyEvent.VK_BACK_SPACE)&&(campo != KeyEvent.VK_DELETE)&&(campo != KeyEvent.VK_ENTER))
        {
            JOptionPane.showMessageDialog(this, "Não inserir caracteres", "Warning", 0);
            evt.consume();
        }
    }//GEN-LAST:event_validar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperaConjuntosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperaConjuntosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperaConjuntosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperaConjuntosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperaConjuntosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDiferenca;
    private javax.swing.JButton jBInstancia;
    private javax.swing.JButton jBInterseccao;
    private javax.swing.JButton jBLimpa;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBUniao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPConjuntos;
    private javax.swing.JPanel jPOperacoes;
    private javax.swing.JPanel jPValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAConjuntos;
    private javax.swing.JTextArea jTAOperacoes;
    private javax.swing.JTextField jTFC1;
    private javax.swing.JTextField jTFC2;
    // End of variables declaration//GEN-END:variables
}
